spring.application.name=ch04_1

spring.h2.console.enabled=true

#spring.datasource.url=jdbc:h2:tcp://localhost/~/test
spring.datasource.url=jdbc:h2:file:C:/Users/hs/allez
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
#spring.datasource.password=
spring.datasource.password=151412

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
# ??: spring.jpa.properties.hibernate.ddl-auto=create-drop
# ?? (?? Spring Boot ??):
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=create-drop
logging.level.org.springframework.web=DEBUG

